import 'package:candy_puzzle/models/puzzle_model.dart';

class PuzzleLocalData {
  static Map<int, PuzzleModel> values = {
    1: PuzzleModel(
      id: 1,
      width: 585.48,
      height: 556,
      duration: Duration(seconds: 60),
      pieces: [
        PuzzlePieceModel(
          id: 1,
          img: 'assets/puzzles/1/1.png',
          correctX: 43,
          correctY: 19.5,
          width: 158.53,
        ),
        PuzzlePieceModel(
          id: 2,
          img: 'assets/puzzles/1/2.png',
          correctX: 310,
          correctY: 24.5,
          width: 201.9,
        ),
        PuzzlePieceModel(
          id: 3,
          img: 'assets/puzzles/1/3.png',
          correctX: 332,
          correctY: 376.5,
          width: 172.99,
        ),
        PuzzlePieceModel(
          id: 4,
          img: 'assets/puzzles/1/4.png',
          correctX: 38,
          correctY: 276.5,
          width: 196.92,
        ),
        PuzzlePieceModel(
          id: 5,
          img: 'assets/puzzles/1/5.png',
          correctX: 411,
          correctY: 166.5,
          width: 174.48,
        ),
        PuzzlePieceModel(
          id: 6,
          img: 'assets/puzzles/1/6.png',
          correctX: 154,
          correctY: 0,
          width: 219.85,
        ),
        PuzzlePieceModel(
          id: 7,
          img: 'assets/puzzles/1/7.png',
          correctX: 312,
          correctY: 155.5,
          width: 166.01,
        ),
        PuzzlePieceModel(
          id: 8,
          img: 'assets/puzzles/1/8.png',
          correctX: 9,
          correctY: 112.5,
          width: 339.99,
        ),
        PuzzlePieceModel(
          id: 9,
          img: 'assets/puzzles/1/9.png',
          correctX: 0,
          correctY: 204.5,
          width: 265.71,
        ),
        PuzzlePieceModel(
          id: 10,
          img: 'assets/puzzles/1/10.png',
          correctX: 61,
          correctY: 303.5,
          width: 215.36,
        ),
        PuzzlePieceModel(
          id: 11,
          img: 'assets/puzzles/1/11.png',
          correctX: 254,
          correctY: 323.5,
          width: 160.52,
        ),
        PuzzlePieceModel(
          id: 12,
          img: 'assets/puzzles/1/12.png',
          correctX: 463,
          correctY: 51.5,
          width: 122.14,
        ),
        PuzzlePieceModel(
          id: 13,
          img: 'assets/puzzles/1/13.png',
          correctX: 438,
          correctY: 345.5,
          width: 140.58,
        ),
      ],
    ),
    2: PuzzleModel(
      id: 2,
      width: 515.49,
      height: 590.04,
      duration: Duration(seconds: 60),
      pieces: [
        PuzzlePieceModel(
          id: 1,
          img: 'assets/puzzles/2/1.png',
          correctX: 0,
          correctY: 295,
          width: 154.05,
        ),
        PuzzlePieceModel(
          id: 2,
          img: 'assets/puzzles/2/2.png',
          correctX: 361,
          correctY: 293,
          width: 154.49,
        ),
        PuzzlePieceModel(
          id: 3,
          img: 'assets/puzzles/2/3.png',
          correctX: 203,
          correctY: 447,
          width: 140.4,
        ),
        PuzzlePieceModel(
          id: 4,
          img: 'assets/puzzles/2/4.png',
          correctX: 152,
          correctY: 0,
          width: 178.26,
        ),
        PuzzlePieceModel(
          id: 5,
          img: 'assets/puzzles/2/5.png',
          correctX: 362,
          correctY: 93,
          width: 151.85,
        ),
        PuzzlePieceModel(
          id: 6,
          img: 'assets/puzzles/2/6.png',
          correctX: 169.25,
          correctY: 215.34,
          width: 178.26,
        ),
        PuzzlePieceModel(
          id: 7,
          img: 'assets/puzzles/2/7.png',
          correctX: 2,
          correctY: 99,
          width: 176.06,
        ),
        PuzzlePieceModel(
          id: 8,
          img: 'assets/puzzles/2/8.png',
          correctX: 255,
          correctY: 9,
          width: 162.85,
        ),
        PuzzlePieceModel(
          id: 9,
          img: 'assets/puzzles/2/9.png',
          correctX: 64.25,
          correctY: 246.34,
          width: 151.85,
        ),
        PuzzlePieceModel(
          id: 10,
          img: 'assets/puzzles/2/10.png',
          correctX: 134.25,
          correctY: 149.34,
          width: 132.92,
        ),
        PuzzlePieceModel(
          id: 11,
          img: 'assets/puzzles/2/11.png',
          correctX: 257,
          correctY: 146,
          width: 113.12,
        ),
        PuzzlePieceModel(
          id: 12,
          img: 'assets/puzzles/2/12.png',
          correctX: 324,
          correctY: 200,
          width: 116.64,
        ),
        PuzzlePieceModel(
          id: 13,
          img: 'assets/puzzles/2/13.png',
          correctX: 433,
          correctY: 204,
          width: 81.87,
        ),
        PuzzlePieceModel(
          id: 14,
          img: 'assets/puzzles/2/14.png',
          correctX: 268,
          correctY: 360,
          width: 230.19,
        ),
        PuzzlePieceModel(
          id: 15,
          img: 'assets/puzzles/2/15.png',
          correctX: 128,
          correctY: 366,
          width: 152.73,
        ),
        PuzzlePieceModel(
          id: 16,
          img: 'assets/puzzles/2/16.png',
          correctX: 0,
          correctY: 445,
          width: 236.35,
        ),
        PuzzlePieceModel(
          id: 17,
          img: 'assets/puzzles/2/17.png',
          correctX: 0,
          correctY: 246,
          width: 66.02,
        ),
        PuzzlePieceModel(
          id: 18,
          img: 'assets/puzzles/2/18.png',
          correctX: 1,
          correctY: 119,
          width: 65.58,
        ),
        PuzzlePieceModel(
          id: 19,
          img: 'assets/puzzles/2/19.png',
          correctX: 95,
          correctY: 0,
          width: 144.37,
        ),
      ],
    ),
    3: PuzzleModel(
      id: 3,
      width: 619,
      height: 618.35,
      duration: Duration(seconds: 60),
      pieces: [
        PuzzlePieceModel(
          id: 1,
          img: 'assets/puzzles/3/1.png',
          correctX: 224,
          correctY: 534,
          width: 169.71,
        ),
        PuzzlePieceModel(
          id: 2,
          img: 'assets/puzzles/3/2.png',
          correctX: 374,
          correctY: 451,
          width: 101.92,
        ),
        PuzzlePieceModel(
          id: 3,
          img: 'assets/puzzles/3/3.png',
          correctX: 132,
          correctY: 434,
          width: 120.5,
        ),
        PuzzlePieceModel(
          id: 4,
          img: 'assets/puzzles/3/4.png',
          correctX: 315,
          correctY: 347,
          width: 96.4,
        ),
        PuzzlePieceModel(
          id: 5,
          img: 'assets/puzzles/3/5.png',
          correctX: 206,
          correctY: 350,
          width: 96.9,
        ),
        PuzzlePieceModel(
          id: 6,
          img: 'assets/puzzles/3/6.png',
          correctX: 0,
          correctY: 169,
          width: 188.28,
        ),
        PuzzlePieceModel(
          id: 7,
          img: 'assets/puzzles/3/7.png',
          correctX: 139,
          correctY: 22,
          width: 148.12,
        ),
        PuzzlePieceModel(
          id: 8,
          img: 'assets/puzzles/3/8.png',
          correctX: 429,
          correctY: 186,
          width: 189.79,
        ),
        PuzzlePieceModel(
          id: 9,
          img: 'assets/puzzles/3/9.png',
          correctX: 333,
          correctY: 24,
          width: 163.68,
        ),
        PuzzlePieceModel(
          id: 10,
          img: 'assets/puzzles/3/10.png',
          correctX: 153,
          correctY: 173,
          width: 155.65,
        ),
        PuzzlePieceModel(
          id: 11,
          img: 'assets/puzzles/3/11.png',
          correctX: 309,
          correctY: 175,
          width: 150.63,
        ),
        PuzzlePieceModel(
          id: 12,
          img: 'assets/puzzles/3/12.png',
          correctX: 69,
          correctY: 263,
          width: 179.75,
        ),
        PuzzlePieceModel(
          id: 13,
          img: 'assets/puzzles/3/13.png',
          correctX: 362,
          correctY: 274,
          width: 178.74,
        ),
        PuzzlePieceModel(
          id: 14,
          img: 'assets/puzzles/3/14.png',
          correctX: 208,
          correctY: 355,
          width: 203.35,
        ),
        PuzzlePieceModel(
          id: 15,
          img: 'assets/puzzles/3/15.png',
          correctX: 207,
          correctY: 178,
          width: 203.35,
        ),
        PuzzlePieceModel(
          id: 16,
          img: 'assets/puzzles/3/16.png',
          correctX: 208,
          correctY: 0,
          width: 203.35,
        ),
      ],
    ),
    4: PuzzleModel(
      id: 4,
      width: 522.52,
      height: 538,
      duration: Duration(seconds: 60),
      pieces: [
        PuzzlePieceModel(
          id: 1,
          img: 'assets/puzzles/4/1.png',
          correctX: 469,
          correctY: 84,
          width: 53.12,
        ),
        PuzzlePieceModel(
          id: 2,
          img: 'assets/puzzles/4/2.png',
          correctX: 396,
          correctY: 182,
          width: 125.95,
        ),
        PuzzlePieceModel(
          id: 3,
          img: 'assets/puzzles/4/3.png',
          correctX: 373,
          correctY: 284,
          width: 149.52,
        ),
        PuzzlePieceModel(
          id: 4,
          img: 'assets/puzzles/4/4.png',
          correctX: 305,
          correctY: 193,
          width: 126.81,
        ),
        PuzzlePieceModel(
          id: 5,
          img: 'assets/puzzles/4/5.png',
          correctX: 226,
          correctY: 256,
          width: 136.24,
        ),
        PuzzlePieceModel(
          id: 6,
          img: 'assets/puzzles/4/6.png',
          correctX: 226,
          correctY: 405,
          width: 170.08,
        ),
        PuzzlePieceModel(
          id: 7,
          img: 'assets/puzzles/4/7.png',
          correctX: 134,
          correctY: 268,
          width: 93.39,
        ),
        PuzzlePieceModel(
          id: 8,
          img: 'assets/puzzles/4/8.png',
          correctX: 0,
          correctY: 141,
          width: 192.36,
        ),
        PuzzlePieceModel(
          id: 9,
          img: 'assets/puzzles/4/9.png',
          correctX: 224,
          correctY: 28,
          width: 193.64,
        ),
        PuzzlePieceModel(
          id: 10,
          img: 'assets/puzzles/4/10.png',
          correctX: 89,
          correctY: 11,
          width: 167.08,
        ),
        PuzzlePieceModel(
          id: 11,
          img: 'assets/puzzles/4/11.png',
          correctX: 214,
          correctY: 0,
          width: 173.51,
        ),
        PuzzlePieceModel(
          id: 12,
          img: 'assets/puzzles/4/12.png',
          correctX: 0,
          correctY: 58,
          width: 134.09,
        ),
        PuzzlePieceModel(
          id: 13,
          img: 'assets/puzzles/4/13.png',
          correctX: 60,
          correctY: 349,
          width: 159.8,
        ),
        PuzzlePieceModel(
          id: 14,
          img: 'assets/puzzles/4/14.png',
          correctX: 298,
          correctY: 269,
          width: 173.51,
        ),
        PuzzlePieceModel(
          id: 15,
          img: 'assets/puzzles/4/15.png',
          correctX: 145,
          correctY: 114,
          width: 173.51,
        ),
        PuzzlePieceModel(
          id: 16,
          img: 'assets/puzzles/4/16.png',
          correctX: 349,
          correctY: 58,
          width: 173.08,
        ),
      ],
    ),
    5: PuzzleModel(
      id: 5,
      width: 589,
      height: 605.47,
      duration: Duration(seconds: 60),
      pieces: [
        PuzzlePieceModel(
          id: 1,
          img: 'assets/puzzles/5/1.png',
          correctX: 204,
          correctY: 0,
          width: 182.05,
        ),
        PuzzlePieceModel(
          id: 2,
          img: 'assets/puzzles/5/2.png',
          correctX: 152,
          correctY: 161,
          width: 294.83,
        ),
        PuzzlePieceModel(
          id: 3,
          img: 'assets/puzzles/5/3.png',
          correctX: 72,
          correctY: 246,
          width: 189.53,
        ),
        PuzzlePieceModel(
          id: 4,
          img: 'assets/puzzles/5/4.png',
          correctX: 208,
          correctY: 301,
          width: 168.47,
        ),
        PuzzlePieceModel(
          id: 5,
          img: 'assets/puzzles/5/5.png',
          correctX: 328,
          correctY: 246,
          width: 189.53,
        ),
        PuzzlePieceModel(
          id: 6,
          img: 'assets/puzzles/5/6.png',
          correctX: 0,
          correctY: 396,
          width: 145.07,
        ),
        PuzzlePieceModel(
          id: 7,
          img: 'assets/puzzles/5/7.png',
          correctX: 78,
          correctY: 397,
          width: 216.68,
        ),
        PuzzlePieceModel(
          id: 8,
          img: 'assets/puzzles/5/8.png',
          correctX: 199,
          correctY: 437,
          width: 189.53,
        ),
        PuzzlePieceModel(
          id: 9,
          img: 'assets/puzzles/5/9.png',
          correctX: 291,
          correctY: 399,
          width: 147.88,
        ),
        PuzzlePieceModel(
          id: 10,
          img: 'assets/puzzles/5/10.png',
          correctX: 396,
          correctY: 396,
          width: 192.81,
        ),
      ],
    ),
    6: PuzzleModel(
      id: 6,
      width: 516,
      height: 514,
      duration: Duration(seconds: 60),
      pieces: [
        PuzzlePieceModel(
          id: 1,
          img: 'assets/puzzles/6/1.png',
          correctX: 169,
          correctY: 0,
          width: 177.13,
        ),
        PuzzlePieceModel(
          id: 2,
          img: 'assets/puzzles/6/2.png',
          correctX: 169,
          correctY: 155,
          width: 177.13,
        ),
        PuzzlePieceModel(
          id: 3,
          img: 'assets/puzzles/6/3.png',
          correctX: 169,
          correctY: 310,
          width: 177.13,
        ),
        PuzzlePieceModel(
          id: 4,
          img: 'assets/puzzles/6/4.png',
          correctX: 339,
          correctY: 235,
          width: 162.26,
        ),
        PuzzlePieceModel(
          id: 5,
          img: 'assets/puzzles/6/5.png',
          correctX: 5,
          correctY: 67,
          width: 150.45,
        ),
        PuzzlePieceModel(
          id: 6,
          img: 'assets/puzzles/6/6.png',
          correctX: 11,
          correctY: 255,
          width: 143.45,
        ),
        PuzzlePieceModel(
          id: 7,
          img: 'assets/puzzles/6/7.png',
          correctX: 84,
          correctY: 0,
          width: 174.94,
        ),
        PuzzlePieceModel(
          id: 8,
          img: 'assets/puzzles/6/8.png',
          correctX: 257,
          correctY: 0,
          width: 199.44,
        ),
        PuzzlePieceModel(
          id: 9,
          img: 'assets/puzzles/6/9.png',
          correctX: 340,
          correctY: 93,
          width: 166.2,
        ),
        PuzzlePieceModel(
          id: 10,
          img: 'assets/puzzles/6/10.png',
          correctX: 437,
          correctY: 188,
          width: 78.72,
        ),
        PuzzlePieceModel(
          id: 11,
          img: 'assets/puzzles/6/11.png',
          correctX: 262,
          correctY: 152,
          width: 159.64,
        ),
        PuzzlePieceModel(
          id: 12,
          img: 'assets/puzzles/6/12.png',
          correctX: 140,
          correctY: 149,
          width: 113.28,
        ),
        PuzzlePieceModel(
          id: 13,
          img: 'assets/puzzles/6/13.png',
          correctX: 0,
          correctY: 208,
          width: 75.66,
        ),
        PuzzlePieceModel(
          id: 14,
          img: 'assets/puzzles/6/14.png',
          correctX: 69,
          correctY: 204,
          width: 121.15,
        ),
        PuzzlePieceModel(
          id: 15,
          img: 'assets/puzzles/6/15.png',
          correctX: 94,
          correctY: 284,
          width: 92.28,
        ),
        PuzzlePieceModel(
          id: 16,
          img: 'assets/puzzles/6/16.png',
          correctX: 125,
          correctY: 310,
          width: 132.96,
        ),
        PuzzlePieceModel(
          id: 17,
          img: 'assets/puzzles/6/17.png',
          correctX: 52,
          correctY: 405,
          width: 134.27,
        ),
        PuzzlePieceModel(
          id: 18,
          img: 'assets/puzzles/6/18.png',
          correctX: 135,
          correctY: 461,
          width: 228.74,
        ),
        PuzzlePieceModel(
          id: 19,
          img: 'assets/puzzles/6/19.png',
          correctX: 314,
          correctY: 384,
          width: 164.45,
        ),
        PuzzlePieceModel(
          id: 20,
          img: 'assets/puzzles/6/20.png',
          correctX: 256,
          correctY: 301,
          width: 116.78,
        ),
      ],
    ),
  };
}
